### PR TITLE
Use 'move-file' to correctly move files across partitions

### PR DESCRIPTION
**Pull request by fpauser**

### CODE REVIEW

**Comment by kellyselden** [comment]
I'm interested in using this if it hanles both EXDEV and broken symlinks. It only supports node 8 though so we can keep this open until node 6 EOL.

**Comment by fpauser** [comment]
Closing in favor of #235

**Comment by fpauser** [comment]
Reopening ;)

**Comment by fpauser** [comment]
Reclosing in favor of #236

**Pull request closed without merging**
